### ISSUE TITLE
Додаткова інформація в лог

### ISSUE THREAD

**Issue by TarasKasprik** [pocket-sunflower/palyanytsya#1]
А яку ще інформацію можна виводити в лог пиріжка, на додаток до тої що вже є?
Скажімо, % успішно відправлених пакетів/мб?

Це на випадок відсутності оператора в пекарні, під час випікання пиріжків.

**Comment by pocket-sunflower** [comment]
Дякуємо за питання!

Наразі є логи зі статусом процесу, а саме кількість відправлених пакетів / байт.

Було б гарно виводити статус цілі (живий сайт, чи вже впав), але для цього потрібен надійний метод перевірки цього самого статусу, зважаючи на різномаїття методів атаки. Якщо є ідеї, як це імплементувати – будемо вдячні.

**Comment by TarasKasprik** [comment]
Я не справжній пекар але в одному з чатів присвячених тестуванню сайтів на витривалість порадили питати відповіді в 53/udp.

https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/portqry-command-line-port-scanner-v2 - саме цей інструмент згадували. 

Це ж на лінукс-заснованих системах щось подібне ну просто гарантовано існує.

**Comment by pocket-sunflower** [comment]
Додали статистику досяжності цілі: https://github.com/pocket-sunflower/palyanytsya/commit/61e16461ff35732f27e54f6002f5a8323486a9c4

Теперь випічка періодично перевіряє статус цілі через Layer 4 та Layer 7 та виводить цю інформацію в лог.

Також додали перевірку проксі-серверів перед запуском тесту. Проксі сервери, які не є досяжними для Layer 4, не будуть використовуватись при атаці – це робить загальний тест більш ефективнішим, бо пакети досягають цілі частіше.

Наразі фільтрування та проксі працюють для методів з Layer 7. Незабаром поширимо це і на метод TCP із Layer 4.

**Comment by pocket-sunflower** [comment]
З оновленням [v2.0.0](https://github.com/pocket-sunflower/palyanytsya/releases/tag/v2.0.0) до Паляниці додана автоматична перевірка статусу цілі, ця інформація тепер виводиться у графічний інтерфейс.

Баг з виводом статусу в Пиріжку виправлений в https://github.com/pocket-sunflower/palyanytsya/commit/ae80a7c2bc7796733fe1354c711f378bc3cc98af.

Тож, закриваємо питання!
